/**
 * Boot a `dsh` profile the way the desktop application does, so the conductor
 * can be verified inside a real Host process.
 *
 * ## Why this exists
 *
 * Invoking `app.asar/lib/desktop-cli.js` directly does **not** reproduce a real
 * boot. The desktop application installs a module-resolution hook before it
 * boots a profile, and the CLI shim does not:
 *
 * - `app.asar/lib/main.js` calls
 *   `installProfilePackageResolver(prepared.bareModuleBaseUrl)` immediately
 *   before `boot(...)`;
 * - `app.asar/lib/desktop-cli.js` never calls it.
 *
 * Without that hook, every row whose `name` is a bare `@deepseek-ai/*` specifier
 * fails to import ("Cannot find package … imported from <profile>") and the
 * whole tree fails to apply with a single `AggregateError` that names no entry.
 * That is an environment artefact, not a plugin defect. This harness installs
 * the same hook first.
 *
 * It also injects two scaffolding rows when `--verify` is requested, so the
 * result is asserted from inside the live Host instead of inferred from logs.
 *
 * ## Usage (Windows, packaged desktop install)
 *
 * ```sh
 * # ELECTRON_RUN_AS_NODE makes the Electron binary behave as plain Node, which
 * # is how the packaged CLI itself runs.
 * set ELECTRON_RUN_AS_NODE=1
 * set DSH_HOME=<isolated home, never the one a live Host is using>
 * set CONDUCTOR_ASAR=<…>/resources/app.asar
 * set CONDUCTOR_PROFILE_DIR=%DSH_HOME%\profiles\<name>
 *
 * "<…>/DSH Desktop.exe" --expose-internals scripts/verify/boot-profile.mjs ^
 *     --profile <name> --verify --port 43917
 * ```
 *
 * Environment:
 * - `CONDUCTOR_ASAR` — absolute path to `resources/app.asar` (required).
 * - `CONDUCTOR_PROFILE_DIR` — absolute path to the profile directory (required).
 * - `CONDUCTOR_PROBE_MODULE` — built entry to import in-process (optional).
 *
 * Flags consumed by this harness (removed before the CLI sees them):
 * - `--verify` — inject the HMR stub and the tree probe.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const asar = process.env['CONDUCTOR_ASAR']
const profileDir = process.env['CONDUCTOR_PROFILE_DIR']

if (asar === undefined || asar.length === 0) {
  process.stderr.write('boot-profile: CONDUCTOR_ASAR is required (path to resources/app.asar)\n')
  process.exit(2)
}
if (profileDir === undefined || profileDir.length === 0) {
  process.stderr.write('boot-profile: CONDUCTOR_PROFILE_DIR is required (path to the profile directory)\n')
  process.exit(2)
}

/** Turn a filesystem path into an importable `file:` URL. */
const moduleUrl = (path) => pathToFileURL(path).href

const argv = process.argv.slice(2)
const verifyIndex = argv.indexOf('--verify')
const verify = verifyIndex !== -1
if (verify) argv.splice(verifyIndex, 1)

if (verify) {
  const overlayPath = join(dirname(profileDir), 'conductor-verify-overlay.yml')
  mkdirSync(dirname(overlayPath), { recursive: true })
  writeFileSync(
    overlayPath,
    [
      '# Generated by scripts/verify/boot-profile.mjs — test scaffolding.',
      '- insert:',
      '    - id: conductor-verify-hmr-stub',
      `      name: '${moduleUrl(join(here, 'hmr-stub.mjs'))}'`,
      '    - id: conductor-verify-probe',
      `      name: '${moduleUrl(join(here, 'tree-probe.mjs'))}'`,
      '',
    ].join('\n'),
    'utf8',
  )
  // The launcher's argument parser stops at the first token it does not know,
  // so launcher flags must precede the booted app's own flags (`--port` and
  // friends). Prepending keeps `--patch` on the launcher's side.
  argv.unshift('--patch', overlayPath)
}

// The loader resolves a row's bare specifier from the profile directory, and a
// plugin's own `@deepseek-ai/*` imports fall back to the desktop installation
// only when this hook is installed.
const { installProfilePackageResolver } = await import(moduleUrl(join(asar, 'lib/module-resolution.js')))
installProfilePackageResolver(moduleUrl(join(profileDir, 'package.json')))

process.argv.splice(2, process.argv.length - 2, ...argv)

const cli = await import(moduleUrl(join(asar, 'lib/desktop-cli.js')))
await cli.runDesktopDshCli()
